
#define Nova_Initialize Nova_Initialize__stub
#define Nova_TrackExecution Nova_TrackExecution__stub
#define GenerateReports GenerateReports__stub
#define AgentDiagnosticsRunAllChecksNova AgentDiagnosticsRunAllChecksNova__stub
#define Nova_NoteAgentExecutionPerformance Nova_NoteAgentExecutionPerformance__stub
#define GenericAgentWriteVersion GenericAgentWriteVersion__stub
