language: c

sudo: required

before_install:
   #- sudo apt-get update
   #- sudo apt-get install -y binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-mingw-w64 mingw-w64
   #- sudo apt-get install autotools-dev
   #- sudo apt-get install -qq wine swig curl

install:
     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash .travis/scripts/install.ubuntu.sh ; fi

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: x86_64-w64-mingw32

script:
     - cd ..
     - pwd
     # PCRE building
     # -------------------------------------------------------------------------
     #- ls -l /usr/x86_64-w64-mingw32/include/
     - git clone https://github.com/coapp-packages/pcre.git
     - cd pcre
     - chmod 777 autogen.sh
     - ./autogen.sh
     - autoreconf -vif
     - env CC=x86_64-w64-mingw32-gcc CFLAGS="-O2 -Wall" ./configure --build=x86_64-w64-mingw32 --host=x86_64 --target=x86_64-w64-mingw32 --prefix=/home/travis/build/malaruik/pcre CFLAGS="-I/usr/x86_64-w64-mingw32/include"
     #- grep -C 3 error config.log
     - make
     - ls -l .libs
     - cd ..
     #- ls -l /usr/x86_64-w64-mingw32/include/sys
     #
     # OpenLDAP -llmdb compilin only
     # -------------------------------------------------------------------------------
     - git clone https://github.com/openldap/openldap.git
     - cd openldap/libraries
     - chmod 777 liblmdb
     - cd liblmdb
     #- make &> output_make.log
     #- grep -C 2 pthread Makefile
     #- sed "s/-pthread/ /g" Makefile >Makefile2
     #- sed "s/-O2 -g/-O2 -g -DSSIZE_MAX=0/g" Makefile2 >Makefile3
     #- cp Makefile3 Makefile
     - make CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar
     #- cp liblmdb.a lmdb.a
     #- chmod 777 liblmdb.a
     #- chmod 777 lmdb.a
     - pwd
     - ls -l
     - cd .. 
     - cd ..
     - cd ..
     - cd core
     #
     # CFENGINE building starts here:
     #
     - which x86_64-w64-mingw32-gcc
     - x86_64-w64-mingw32-gcc --version
     - autoreconf -vif
     - env CC=x86_64-w64-mingw32-gcc ./configure --build=x86_64-w64-mingw32 --host=x86_64 --target=x86_64-w64-mingw32 --with-lmdb=/home/travis/build/malaruik/openldap/libraries/liblmdb CFLAGS="-I/home/travis/build/malaruik/openldap/libraries/liblmdb -lmsvcrt -g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1 -I/usr/x86_64-w64-mingw32/include/" LDFLAGS="-lpcre -L/home/travis/build/malaruik/openldap/libraries/liblmdb"
     - grep -C 2 error config.log
     #- make

env:

