language: c

sudo: required

before_install:
   #- sudo apt-get update
   #- sudo apt-get install -y binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-mingw-w64 mingw-w64
   #- sudo apt-get install autotools-dev
   #- sudo apt-get install -qq wine swig curl
   #- sudo apt-get install mingw32-binutils
   - sudo apt-get install pkg-config


install:
     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash .travis/scripts/install.ubuntu.sh ; fi
     #- export CFLAGS="-I/usr/include/mysql -I/usr/include/mysql/mysql"
     #- export LDFLAGS="-Ifaas"
     - sudo ln -s /usr/bin/x86_64-w64-mingw32-windres /usr/bin/windres

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: x86_64-w64-mingw32

script:
     - ls -l
     - cd ..
     - pwd
     #
     # -------------------------------------------------------------------------
     #  PCRE building
     # -------------------------------------------------------------------------
     - ls -l /usr/x86_64-w64-mingw32/include/winver.h
     # - cp /usr/x86_64-w64-mingw32/include/winver.h /home/build/travis/malaruik/openssl/include/winver.h 
    #- ls -l /usr/include/mysql
     - git clone https://github.com/coapp-packages/pcre.git
     - cd pcre
     - chmod 777 autogen.sh
     - ./autogen.sh
     - autoreconf -vif
     - env CC=x86_64-w64-mingw32-gcc CFLAGS="-O2 -Wall" ./configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/home/travis/build/malaruik/pcre CFLAGS="-I/usr/x86_64-w64-mingw32/include"
     #- grep -C 3 error config.log
     - make
     - ls -l .libs
     - cd ..
     #
     # --------------------------------------------------------------------------
     #  OpenSSL building
     # --------------------------------------------------------------------------
     - git clone https://github.com/openssl/openssl.git --branch master
     - sudo cp /usr/x86_64-w64-mingw32/include/winver.h /home/build/travis/malaruik/openssl/include/winver.h 
     - sudo chmod 777 openssl
     - cd openssl
     - pwd
     - sudo chmod 777 include
     - sudo chmod 777 include/openssl
     - sudo chmod 777 include/openssl/.
     - ls -l ./include/openssl
     - env CC=x86_64-w64-mingw32-gcc ./Configure mingw64 shared -L../../share/mingw-w64/include --prefix=/home/travis/build/malaruik/openssl --openssldir=/home/travis/build/malaruik/openssl -I../../share/mingw-w64/include
     - make depend
     - make 2>&1 > build.log
     #- grep -C 3 error build.log
     - ls -l
     - make install
     - ls -l
     - tail -40 build.log
     - pwd
     - ls -l ./include
     - cd ..
     #
     # -----------------------------------------------------------------------------
     # OpenLDAP -llmdb compiling only
     # -----------------------------------------------------------------------------
     - git clone https://github.com/openldap/openldap.git --branch master
     - cd openldap/libraries
     - ls -l
     - cd liblmdb
     - sed 's/-shared/-shared -Wl,-Bsymbolic/g' Makefile >Makefile2
     #    - sed 's/.so/.dll/g' Makefile2 >Makefile3
     - cp Makefile2 Makefile
     - env make CC=x86_64-w64-mingw32-gcc
     - chmod 777 liblmdb.a
     - sudo make install
     - pwd
     #- ls -l
     - cd .. 
     - cd ..
     - cd ..
     - cd core
     # -----------------------------------------------------------------------
     # CFENGINE building starts here:
     # -----------------------------------------------------------------------
     #- which x86_64-w64-mingw32-gcc
     #- x86_64-w64-mingw32-gcc --version
     - sed 's/WITH_LMDB = 1/WITH_LMDB = 0/g' configure.ac >configure.ac2
     - cp configure.ac2 configure.ac
     - autoreconf -vif
     - env CC=x86_64-w64-mingw32-gcc ./configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-openssl=/home/travis/build/malaruik/openssl --with-libevent=$SYSROOT --with-pcre=/home/travis/build/malaruik/pcre --with-lmdb=/home/travis/build/malaruik/openldap/libraries/liblmdb --prefix=/home/travis/build/malaruik/core CFLAGS="-I/usr/x86_64-w64-mingw32/include -I/usr/include/mysql -I/usr/inlcude/mysql/mysql -I/home/travis/build/malaruik/pcre -I/home/travis/build/malaruik/pcre/.libs -I/home/travis/build/malaruik/openldap -I/home/travis/build/malaruik/openldap/libraries/liblmdb -I../../openssl/include -lmsvcrt -g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1" LDFLAGS="-L/home/travis/build/malaruik/openssl -L/home/travis/build/malaruik/pcre/.libs -L/home/travis/build/malaruik/openldap/libraries/liblmdb -lssl -lcrypto -llmdb -lpcre"
     - grep -C 3 error config.log
     #- tail -60 config.log
     #- make
     #-----------------------------------------------------------------------
     #
     #-----------------------------------------------------------------------

env:

