language: cpp

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y mingw-w64
   - sudo apt-get install ldap-utils libldap-2.4-2 libldap2-dev

install:
     - git clone https://github.com/openldap/openldap.git
     - cd openldap
     - ./configure
     - make &> output_make.log
     - ls -l ./libraries
     - cd ./libraries/liblmdb
     - sudo make install
     - ls -l
     - cd ..
     - cd ..
     - cd ..

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: x86_64-w64-mingw32-gcc

script:
     - ./autogen.sh --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-lmdb=/openldap/libraries/liblmdb CFLAGS="-Wimplicit-function-declaration -g -Wall -Wno-pointer-sign -i/usr/x86_64-w64-mingw32/sys-root/mingw/include/ -I/openldap/libraries/liblmdb"
     - echo $CC
     - make

env:

