language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine swig curl
  - sudo apt-get install -qq mingw32
  - sudo apt-get install ldap-utils libldap-2.4-2 libldap2-dev

install:
     - git clone https://github.com/openldap/openldap.git
     - cd openldap
     - ./configure
     - make &> output_make.log
     - ls -l ./libraries
     - cd ./libraries/liblmdb
     - sudo make install
     - ls -l
     - cd ..
     - cd ..
     - cd ..

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: clang

script: 
     - ./autogen.sh --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-lmdb=/openldap/libraries/liblmdb --disable-slapd CFLAGS="-Wimplicit-function-declaration -I/openldap/libraries/liblmdb"
     - make

env:

