language: bash


before_install:
   - sudo apt-get install -y binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-mingw-w64 mingw-w64
   - sudo apt-get install ldap-utils libldap-2.4-2 libldap2-dev

install:
     - export CC=x86_64-w64-mingw32-gcc
     - export CFLAGS="-g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1 -I/usr/x86_64-w64-mingw32/include/ -I/include/ -I/include/ac"
     - export LDFLAGS="-L/usr/x86_64-w64-mingw32/lib/"

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: x86_64-w64-mingw32

script:
     - pwd
     #- ls -l /usr/x86_64-w64-mingw32/include/
     - git clone https://github.com/openldap/openldap.git
     #- cd openldap
     #- env CC=/usr/bin/x86_64-w64-mingw32-gcc ./configure mingw64 shared --build=x86_64-w64-mingw32 --host=x86_64 --target=x86_64-w64-mingw32
     #- grep -C 4 error config.log
     #- make &> output_make.log
     #- make
     #- ls -l ./libraries
     #- cd ./libraries/liblmdb
     #- sudo make install
     #- ls -l
     #- cd ..
     #- cd ..
     #- cd ..
     - which x86_64-w64-mingw32-gcc
     - x86_64-w64-mingw32-gcc --version
     - /configure mingw64 shared --build=x86_64-w64-mingw32 --host=x86_64 --target=x86_64-w64-mingw32 --disable-pthreads --with-lmdb=/openldap/libraries/liblmdb
     - grep -C 2 error config.log
     - echo $CCLD
     - make
env:

