language: bash


before_install:
   - sudo apt-get install -y binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-mingw-w64 mingw-w64
   - sudo apt-get install autotools-dev
   - sudo apt-get install -qq wine swig curl
   - sudo apt-get install ldap-utils libldap-2.4-2 libldap2-dev
   - sudo apt-get install gcc-multilib

install:
     #- export CC=x86_64-w64-mingw32-gcc
     #- export CFLAGS="-g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1 -I/usr/x86_64-w64-mingw32/include/ -I./pthread-win32/ -I./openldap/include/ -I./openldap/include/ac"
     #- export LDFLAGS="-L/pthread-win32 -L/usr/x86_64-w64-mingw32/lib/"
     #- export LD_LIBRARY_PATH="/pthread-win32/"

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: x86_64-w64-mingw32

script:
     - pwd
     - cd ..
     - ls -l /usr/include
     #- ls -l /usr/x86_64-w64-mingw32/include
     # ----------------------
     - git clone https://github.com/GerHobbelt/pthread-win32.git
     - cd ./pthread-win32
     - make CROSS=x86_64-w64-mingw32- clean GC-static
     - ls -l *.a
     - cp libpthreadGC2.a ..
     - cd ..
     # -------------------
     - cd core
     #- autoreconf -vif
     #- env CC=x86_64-w64-mingw32-gcc ./configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-lmdb=/openldap/libraries/liblmdb --with-pthreads=/pthread-win32 CFLAGS="-g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1 -I/usr/x86_64-w64-mingw32/include/ -I/openldap/libraries/liblmdb" LDFLAGS=""
     - cd ..
   # PCRE
     - git clone https://github.com/coapp-packages/pcre.git
     - cd pcre
     - chmod 777 autogen.sh
     - ./autogen.sh
     - autoreconf -vif
     - env CC=x86_64-w64-mingw32-gcc CFLAGS="-O2 -Wall" ./configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/home/travis/build/malaruik/pcre
     - make
     - ls -l .libs
     - cd ..
     #-------------------------
     #- ls -l /usr/x86_64-w64-mingw32/include/
     - ls -l ./core/libutils
     - git clone https://github.com/openldap/openldap.git
     - cd openldap
     #-ls -l ./include/ac
     - env CC=x86_64-w64-mingw32-gcc ./configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-slapd --with-yielding_select=no CFLAGS="-I/usr/include -I/include/ac -I/home/travis/build/malaruik/pthread-win32 -I/home/travis/build/malaruik/pcre/" LDFLAGS="-L/home/travis/build/malaruik/pcre/.libs -lws2_32"
     - grep -C 4 error config.log
     #- make &> output_make.log
     #- grep -C 4 error config.log
     #- ls -l
     #- pwd
     #- cd ..
     #- cd ..
     #- cd ..
     #- which x86_64-w64-mingw32-gcc
     #- x86_64-w64-mingw32-gcc --version
     #- autoreconf -vif
     #- env CC=x86_64-w64-mingw32-gcc ./configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-lmdb=/openldap/libraries/liblmdb --with-pthreads=/pthread-win32 CFLAGS="-g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1 -I/usr/x86_64-w64-mingw32/include/ -I/openldap/libraries/liblmdb" LDFLAGS=""
     #- grep -C 2 error config.log
     #- make

env:

