language: c++

before_install: sudo apt-get install mingw-w64

os: linux

compiler: x86_64-w64-mingw32-gcc

script: ./autogen.sh --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32  --target=x86_64-w64-mingw32 CFLAGS="-i/usr/x86_64-w64-mingw32/sys-root/mingw/include/ -D__USE_MINGW_ANSI_STDIO=1"

env:

