language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine swig curl
  - sudo apt-get install -qq mingw32
  - sudo apt-get install ldap-utils libldap-2.4-2

os: linux

compiler: clang

script: ./autogen.sh mingw64 shared --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32  --target=x86_64-w64-mingw32 --with-lmdb=/openldap/libraries/liblmdp CFLAGS="-i/usr/x86_64-w64-mingw32/sys-root/mingw/include/ -D__USE_MINGW_ANSI_STDIO=1"

env:

