language: c



before_install:


os:
 linux


compiler: gcc


env: 
  - CONFIG_OPTS="" DESTDIR="_install" TESTS="-test_fuzz"


matrix:
  include:
    - os: linux
    addons:
             apt:
 
                packages:
                   - binutils-mingw-w64
 
                  - gcc-mingw-w64
 
           compiler: i686-w64-mingw32-gcc



