language: c

before_install:

os: linux

addons:
        apt:
          packages:
            - mingw-w64

script: ./autogen.sh --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-slapd CFLAGS="-i/usr/x86_64-w64-mingw32/sys-root/mingw/include/ -D__USE_MINGW_ANSI_STDIO=1"

compiler: x86_64-w64-mingw32

env:

