language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine swig curl
  - sudo apt-get install -qq mingw32

os: linux

compiler: clang

script: ./autogen.sh --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disaple-slapd

env:

