language: bash


before_install:
   - sudo apt-get install -y binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-mingw-w64 mingw-w64
   - sudo apt-get install autotools-dev

install:
     - export CC=x86_64-w64-mingw32-gcc
     - export CFLAGS="-g -Wall -Wno-pointer-sign -Wimplicit-function-declaration -Wunused-parameter -Wno-format -O2 -DNDEBUG -D__MSVCRT_VERSION__=0x0700 -D__USE_MINGW_ANSI_STDIO=1 -I/usr/x86_64-w64-mingw32/include/ -I./pthread-win32/ -I./openldap/include/ -I./openldap/include/ac"
     - export LDFLAGS="-L/pthread-win32 -L/usr/x86_64-w64-mingw32/lib/"
     - export LD_LIBRARY_PATH="/pthread-win32/"

addons:
  apt:
    packages:
      - cmake

os: linux

compiler: x86_64-w64-mingw32

script:
     - pwd
     - git clone https://github.com/GerHobbelt/pthread-win32.git
     - cd ./pthread-win32
     - make CROSS=x86_64-w64-mingw32- clean GC
     - ls -l
     - cd ..
     #- ls -l /usr/x86_64-w64-mingw32/include/
     #- git clone https://github.com/openldap/openldap.git
     #- cd openldap
     #- ls -l ./include/
     #- env CC=/usr/bin/x86_64-w64-mingw32-gcc ./configure mingw64 shared --build=x86_64-w64-mingw32 --host=x86_64 --target=x86_64-w64-mingw32
     #- grep -C 4 error config.log
     #- make &> output_make.log
     #- make
     #- ls -l ./libraries
     #- cd ./libraries/liblmdb
     #- sudo make install
     #- ls -l
     #- cd ..
     #- cd ..
     #- cd ..
     - which x86_64-w64-mingw32-gcc
     - x86_64-w64-mingw32-gcc --version
     - autoreconf -vif
     - ./configure mingw64 --build=x86_64-w64-mingw32 --host=x86_64 --target=x86_64-w64-mingw32 CFLAGS="-O2 -I/pthread-win32/" LDFLAGS="-L/pthread-win32/ -lpthreadGC2"
     - grep -C 2 error config.log
     - echo $CCLD
     - make
env:

